import { chromium } from "@playwright/test";
import { launchOptions, shoot } from "./env.mjs";
const b = await chromium.launch(launchOptions());
const page = await b.newPage({ viewport: { width: 1440, height: 900 } });
page.on("pageerror", (e) => console.log("PAGEERROR:", String(e).slice(0, 300)));
await page.goto("http://localhost:4173/?capture=1&ss=2&scenario=launch", { waitUntil: "load" });
await page.waitForFunction(() => window.__city?.ready === true, null, { timeout: 180000 });
await page.evaluate(() => window.__city.frame("city", 6));
await shoot(page, "play-rest.png");
console.log("info:", JSON.stringify(await page.evaluate(() => window.__city.info())));
await page.click('[data-action="primary"]', { force: true });
await page.waitForTimeout(400);
await page.evaluate(() => window.__city.renderFrame(6));
await shoot(page, "play-panel.png");
console.log("panel:", (await page.locator(".dossier").innerText()).slice(0, 400).replace(/\n/g, " | "));
await b.close();
