/**
 * Regenerates `tests/fixtures/whop-openapi-scopes.json` from Whop's published
 * OpenAPI documents.
 *
 * The fixture is the committed baseline that `whop-sandbox.spec.ts` checks the
 * capability manifest against, so a scope change on Whop's side surfaces as a
 * failing test rather than a runtime 403.
 *
 *   node --experimental-strip-types scripts/extract-openapi-scopes.ts
 */

import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const SPECS = {
  native: "https://docs.whop.com/openapi/api-v1-native.json",
  stable: "https://docs.whop.com/openapi/api-v1-stable.json",
} as const;

/** Operations the manifest depends on, keyed by `METHOD path`. */
const TRACKED: Record<string, keyof typeof SPECS> = {
  "GET /permissions": "native",
  "GET /accounts": "native",
  "GET /products": "native",
  "POST /products": "native",
  "GET /products/{id}": "native",
  "GET /plans": "native",
  "GET /members": "native",
  "GET /memberships": "native",
  "GET /payments": "native",
  "GET /stats": "native",
  "GET /stats/{metric}": "native",
  "GET /webhooks": "native",
  "POST /webhooks": "native",
  "GET /affiliates": "stable",
};

interface OpenApiDocument {
  info: { "x-api-version-date"?: string };
  servers?: { url: string; description?: string }[];
  paths: Record<string, Record<string, { security?: Record<string, string[]>[] }>>;
}

async function loadSpec(url: string): Promise<OpenApiDocument> {
  const response = await fetch(url);
  if (!response.ok) throw new Error(`${url} -> HTTP ${response.status}`);
  return (await response.json()) as OpenApiDocument;
}

/**
 * OpenAPI security is a list of alternatives; the scopes inside one
 * alternative are all required together. An alternative with no scopes means
 * "any authenticated bearer", and `{}` means "no authentication at all".
 */
function readSecurity(op: { security?: Record<string, string[]>[] } | undefined) {
  if (!op) return undefined;
  const alternatives = (op.security ?? []).map((requirement) => {
    const entries = Object.entries(requirement);
    if (entries.length === 0) return { auth: "none" as const, scopes: [] };
    return { auth: "bearer" as const, scopes: entries.flatMap(([, scopes]) => scopes).sort() };
  });
  return alternatives;
}

async function main(): Promise<void> {
  const specs = {
    native: await loadSpec(SPECS.native),
    stable: await loadSpec(SPECS.stable),
  };

  const operations: Record<string, unknown> = {};
  const missing: string[] = [];

  for (const [key, surface] of Object.entries(TRACKED)) {
    const [method, apiPath] = key.split(" ") as [string, string];
    const op = specs[surface].paths[apiPath]?.[method.toLowerCase()];
    if (!op) {
      missing.push(key);
      continue;
    }
    operations[key] = { surface, security: readSecurity(op) };
  }

  if (missing.length > 0) {
    throw new Error(`Tracked operations absent from the specs: ${missing.join(", ")}`);
  }

  const fixture = {
    note: "Generated by scripts/extract-openapi-scopes.ts. Do not hand-edit.",
    generatedFrom: SPECS,
    apiVersionDate: specs.native.info["x-api-version-date"],
    servers: specs.native.servers,
    operations,
  };

  const outPath = path.resolve(
    path.dirname(fileURLToPath(import.meta.url)),
    "../tests/fixtures/whop-openapi-scopes.json",
  );
  await writeFile(outPath, `${JSON.stringify(fixture, null, 2)}\n`, "utf8");
  console.log(`Wrote ${outPath}`);
  console.log(`API version date: ${fixture.apiVersionDate}`);
}

await main();
